Drop py27
latchset/jwcrypto pull request #219
Opened 2021-06-08 18:49 UTC by simo5

RIP python2

2021-06-09 18:45 UTC, simo5 commented
@tiran do you think there is any other python2isms I should get rid off here?

2021-06-10 07:43 UTC, tiran requested changes

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwa.py
> +            # pylint: disable=raise-missing-from
Python 3 does exception chaining. I recommend to add ``raise InvalidJWAAlgorithm(...) from None`` unless you want to show the inner exception to your users.

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for name, val in iter(_OKP_CURVES_TABLE.items()):
``items`` returns an iterator.

```suggestion
        for name, val in _OKP_CURVES_TABLE.items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for name, val in iter(JWKValuesRegistry[kty].items()):
```suggestion
        for name, val in JWKValuesRegistry[kty].items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for name, val in iter(JWKValuesRegistry[t['kty']].items()):
```suggestion
        for name, val in JWKValuesRegistry[t['kty']].items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for k, v in iter(dict(*args, **kwargs).items()):
```suggestion
        for k, v in dict(*args, **kwargs).items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
>              raise AttributeError
```suggestion
            raise AttributeError(key) from None
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
>              raise AttributeError
```suggestion
            raise AttributeError(key) from None
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for k, v in iter(dict(*args, **kwargs).items()):
```suggestion
        for k, v in dict(*args, **kwargs).items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for k, v in iter(self.items()):
```suggestion
        for k, v in self.items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jwk.py
> +        for k, v in iter(self.items()):
```suggestion
        for k, v in self.items():
```

2021-06-10 07:43 UTC, tiran commented on jwcrypto/jws.py
>                      raise InvalidJWSObject('Unrecognized representation')
```suggestion
                    # pylint: disable=raise-missing-from
                    raise InvalidJWSObject('Unrecognized representation') from None
```

2021-06-10 13:25 UTC, simo5 commented
@tiran thanks for pointing out the issue with iter and that I could use 'from None'. I definitely want to use from None in those places.
I think I fixed all the points raised in the last force push.

2021-07-13 21:53 UTC, merged